# Site settings
name: Hupfen
description: "Zoe Landon: Web developer, product designer, internet rabbit"
author:
  name: Zoe Landon
  email: zoe@leporidaemedia.com
  github: hupfen
  twitter: hupfen
baseurl: ""

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
