# Site settings
title: Hupfen
header-img: img/home-bg.jpg
email: zoe@hupfen.com
description: "A blog and portfolio for Zoe Landon, web developer and internet rabbit"
baseurl: ""
url: "http://hupfen.com"
twitter_username: hupfen
github_username:  hupfen

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
